### ISSUE TITLE
"ドキュメント"のリンクが切れている

### ISSUE THREAD

**Issue by mouse484** [discordjs-japan/homepage#100]
#99 と同じ？

https://github.com/discordjs-japan/homepage/blob/c6bbeafa2363fbc5c01f81cd1a4a7668e05f3e26/components/layout/home/Footer.vue#L98-L101

**Comment by InkoHX** [comment]
今はもう使ってないドメインなんだけど、`i18n.djs-jpn.tk`って元々Discord.js Docsを翻訳したものを載せてた。
Netlifyかなんかでyutaさんがホスティングしてたけど、今いないから実質ないに等しい状態

**Comment by mouse484** [comment]
だよね 新しくホスティングしてもいいけど結局翻訳もあんまり進んでなさそうだし
