### ISSUE TITLE
提案: 静的サイトホスティングサービスを活用する

### ISSUE THREAD

**Issue by mouse484** [discordjs-japan/homepage#96]
PRやコミット/ブランチに対するプレビューが存在していない、静的サイトホスティングサービスなどを使えばプレビューが使えるからできるなら替えたい感ある。

1. Vercel
  	- 個人は完全無料、チームは有料。
  	- オープンソースプランは無料で使えるの一度コンタクトを取ってみないといけない
  		- [Can Vercel sponsor my open source project? - Vercel Support Article](https://vercel.com/support/articles/can-vercel-sponsor-my-open-source-project)
  	- 個人的に結構使ってる
2. Netlify
	- 個人プランでOrganizationのGitと連携できるからそれなら無料。
	- チームを作るならオープンソースプランのコンタクトを取らないといけない。
		- [Open Source Plan Policy](https://www.netlify.com/legal/open-source-policy/) 
3. Cloudflare Pages
	- 使ったこと無い
	- でもコストがほとんどの場合かからないから上のオープンソースプラン使えなかったら選択肢として悪くないかも
	- 新しいから情報が少ない、1,2と比べるとビルドの速度が少し遅いのが弱点

**Comment by InkoHX** [comment]
Netlifyはフォームから情報を入力して申請する感じっぽいから楽そう
