### ISSUE TITLE
ドキュメントのガイド翻訳やドキュメント国際化のリンクが切れている

### ISSUE THREAD

**Issue by mouse484** [discordjs-japan/homepage#99]
/i18nが存在しない
これから作る予定？それとも間違い？
https://github.com/discordjs-japan/homepage/blob/62a95884a1a71716bb98e81c72eda6abb92c00bd/pages/index.vue#L81

**Comment by mouse484** [comment]
https://discordjs-japan.org/i18n

**Comment by InkoHX** [comment]
おそらく作りかけ
